### ISSUE TITLE
Invoking NeuralNetwork from command line

### ISSUE THREAD

**Issue by christopher-beckham** [amten/NeuralNetwork#1]
Hi there,

First of all, thanks for writing this! I'm currently trying this out for the Kaggle digits competition. I was particular excited by the results you managed to get.

I'm having trouble invoking this algorithm from command-line however, and _I think_ that may have to do with the fact that your algorithm's flag for the number of threads is `-t`, whereas this is what Weka uses to denote the training file.

For example:

```
java -Xmx6500M -cp $WEKA_LATEST weka.Run weka.classifiers.functions.NeuralNetwork -lr 0.0 -wp 1.0E-8 -i 250 -bs 1 -t 4 -hl 20-5-5-2-2,100-5-5-2-2 -di 0.2 -dh 0.5 -iw 0 -t trainfile.arff -no-cv -d modelfile.model
```

As you can see, `-t` is also used to denote the training .arff file.

Removing `-t 4` won't fix the problem, either.

Anyways a fix for this would be awesome, since you can end up saving quite a bit of memory using Weka from the command-line (as you don't have to load the entire dataset into memory which is what happens with the GUI).

Perhaps there's a workaround for this that won't involve any changing of the code, but I don't know of anything like this yet. :)

Cheers

**Comment by amten** [comment]
Hey there!

Thanks for pointing this out. I only tried it in Wekas explorer, so I didn't know that the flag "-t" is used by Weka for specifying a training file from the command line.

I guess it would be simple to fix this by renaming the flag to "-th" or something like that. I will try to fix that tomorrow. I'll also fix the problem with having to specify all options. It would be better if default options were used for the ones not specified.

Cheers,
/Johannes

**Comment by amten** [comment]
Fixed.

Besides the "-t" flag for number of threads, the "-i" flag for maximum number of iterations also coincided with a flag used in the Weka CLI. These have now been renamed to "-th" and "-mi" instead and I am now able to run the classifier from the Weka CLI.

I also implemented a main()-method, so you can call "java weka.classifiers.functions.NeuralNetwork" directly instead of "java weka.Run weka.classifiers.functions.NeuralNetwork"
